### ISSUE TITLE
"Upgrade Required" . this message is displayed after installation.

### ISSUE THREAD

**Issue by tomzcn** [calcit-lang/editor#35]

**Comment by tiye** [comment]
need more details.

but displaying upgrade notice is intentional. Calcit Editor might have updates when Calcit itself is updated. If server and client is not matched, there could be problems.

**Comment by tomzcn** [comment]
> need more details.
> 
> 但显示升级通知是有意为之。当 Calcit 本身更新时，Calcit 编辑器可能会有更新。如果服务器和客户端不匹配，则可能存在问题。

我打开github codespaces。

运行下面的命令。

npm i -g calcit-editor
calcit-editor

然后

curl http://127.0.0.1:6001

得到这个错误

Upgrade Required

**Comment by tiye** [comment]
`6001` 端口启动了一个 WebSocket 服务, 通过 curl 去访问, 确实会变成这个提示... 这个服务是编辑器的后端, 前端需要用 https://repo.calcit-lang.org/editor/ 进行连接. 如果是在远程, 需要通过 `?host=<IP address>&port=6001` 尝试连接(但涉及 SSL 协议, 远程连接可能会遇到其他问题).

**Comment by tiye** [comment]
另外当前仓库的安装包是 `@calcit/editor`, 是 Calcit 脚本语言的编辑器, 输出文件是 `compact.cirru`. 前面那个 `calcit-editor` 是之前老版本, 生成的目标是 ClojureScript 代码. 两个场景不一样, 后者具体按照 https://github.com/Cirru/calcit-editor 来.

**Comment by tiye** [comment]
浏览器上玩玩可以了 http://repo.calcit-lang.org/calcit-wasm-play/ 😄

**Comment by tomzcn** [comment]
收到
